import { Also, ArrayOf, AutoCastable, ParamValidationError, Pick, Prop } from 'civkit/civ-rpc';
import { AbstractLLM, DependsOnOptions } from './base';
import { LLMFunctionCallRequest, LLMFunctionCallResponse, LLMMessage, LLMModelOptions, PromptChunk, chatMLEncode, parseJSON, stringPromptChunks } from './misc';
import { OpenAIHTTP } from '../../3rd-party/openai';
import { EnvConfig } from '../envconfig';
import _ from 'lodash';
import { Readable, Transform, TransformCallback } from 'stream';
import { injectable } from 'tsyringe';

import { countGPTToken } from "../../utils/openai";
import { GlobalLogger } from "../logger";
import type { ChatCompletion, ChatCompletionChunk, ChatCompletionMessageToolCall } from 'openai/resources/index';
import { TempFileManager } from '../temp-file';
import { readFile } from 'fs/promises';
// import { OpenAICompatHTTP } from '../../3rd-party/openai-compat';
import { AsyncLocalContext } from '../async-context';
import { HTTPServiceRequestOptions } from 'civkit/http';
import { downloadFile } from 'civkit/download';
import { mimeOf } from 'civkit/mime';
import { HarmfulContentError } from '../errors';


export enum CHAT_GPT_ROLE {
    USER = 'user',
    SYSTEM = 'system',
    ASSISTANT = 'assistant',
    FUNCTION = 'function',
    TOOL = 'tool',
}

export enum CHAT_GPT_FUNCTION_CALL_MODE {
    NONE = 'none',
    AUTO = 'auto',
}

export interface ChatGPTFunctionCall {
    name: string;
    // The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
    arguments: string;
}

export class ChatGPTFunctionCall extends AutoCastable {
    @Prop({
        desc: 'The name of the function to call.',
        required: true,
    })
    name!: string;

    @Prop({
        desc: 'The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.',
        required: true,
    })
    arguments!: string;
}

export class ChatGPTToolCall_Function extends AutoCastable {
    @Prop({
        desc: 'The ID of the tool call',
        required: true,
    })
    id!: string;

    @Prop({
        desc: 'The type of the tool. Currently, only function is supported.',
        required: true,
        default: 'function',
    })
    type!: string;

    @Prop({
        desc: `The function that the model called.`,
        required: true,
    })
    function!: ChatGPTFunctionCall;

    @Prop()
    index?: number;
}

export class ChatGPTMessageTextChunk extends AutoCastable {
    @Prop({
        desc: 'Type of the message chunk',
        default: 'text',
        required: true,
        validate: (x) => x === 'text'
    })
    type!: 'text';

    @Prop({
        desc: 'The content of the message chunk',
        required: true,
    })
    text!: string;
}

export enum CHAT_GPT_IMAGE_DETAIL {
    AUTO = 'auto',
    LOW = 'low',
    HIGH = 'high',
}
export class ChatGPTMessageImageUrl extends AutoCastable {
    @Prop({
        desc: 'Either a URL of the image or the base64 encoded image data.',
    })
    url?: string;

    @Prop({
        desc: 'Either a URL of the image or the base64 encoded image data.',
        type: CHAT_GPT_IMAGE_DETAIL,
        default: CHAT_GPT_IMAGE_DETAIL.AUTO,
    })
    detail?: CHAT_GPT_IMAGE_DETAIL | 'string';
}
export class ChatGPTMessageImageUrlChunk extends AutoCastable {
    @Prop({
        desc: 'Type of the message chunk',
        default: 'image_url',
        required: true,
        validate: (x) => x === 'image_url'
    })
    type!: 'image_url';

    @Prop({
        desc: 'The content of the image url chunk',
        required: true,
    })
    image_url!: ChatGPTMessageImageUrl;
}

export class ChatGPTMessage extends AutoCastable {
    @Prop({
        desc: 'The role of the author of this message.',
        required: true,
        default: 'user',
        type: CHAT_GPT_ROLE,
    })
    role!: CHAT_GPT_ROLE | string;

    @Prop({
        desc: 'The contents of the message',
        default: '',
        nullable: true,
        type: [ArrayOf(ChatGPTMessageTextChunk, ChatGPTMessageImageUrlChunk), String],
    })
    content!: string | (ChatGPTMessageTextChunk | ChatGPTMessageImageUrlChunk)[];

    @Prop({
        desc: 'The name of the user in a multi-user chat'
    })
    name?: string;

    @Prop({
        desc: 'The tool calls generated by the model, such as function calls.',
        arrayOf: [ChatGPTToolCall_Function],
    })
    tool_calls?: (ChatGPTToolCall_Function)[];

    @Prop({
        desc: 'The name and arguments of a function that should be called, as generated by the model.',
    })
    function_call?: ChatGPTFunctionCall;

    @Prop({
        desc: 'Tool call that this message is responding to.',
    })
    tool_call_id?: string;
}

@Also({
    validate: (i: ChatGPTMessage) => (i.role === CHAT_GPT_ROLE.FUNCTION) ? Boolean(i.name) : true
})
export class ClassicChatGPTMessage extends ChatGPTMessage {
    @Prop({
        desc: 'The contents of the message',
        default: '',
        nullable: true,
    })
    override content!: string;
}

export class ChatGPTFunctionDescriber extends AutoCastable {
    @Prop({
        desc: 'The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.',
        validate: (x: string) => /[a-zA-Z0-9_]{1,64}/.test(x),
        required: true
    })
    name!: string;

    @Prop({
        desc: 'The description of what the function does.',
        default: ''
    })
    description!: string;

    @Prop({
        desc: 'The parameters the functions accepts, described as a JSON Schema object. See the guide for examples, and the JSON Schema reference for documentation about the format.',
        required: true,
    })
    parameters!: object;
}

export enum CHAT_GPT_RESPONSE_FORMAT {
    TEXT = 'text',
    JSON_OBJECT = 'json_object',
}

export class ChatGPTResponseFormat extends AutoCastable {
    @Prop({
        required: true,
        default: CHAT_GPT_RESPONSE_FORMAT.TEXT,
        type: CHAT_GPT_RESPONSE_FORMAT,
    })
    type!: CHAT_GPT_RESPONSE_FORMAT | string;
}

export enum CHAT_GPT_TOOL_TYPE {
    FUNCTION = 'function',
}

export class ChatGPTToolDescriber_Function extends AutoCastable {
    @Prop({
        required: true,
        default: CHAT_GPT_TOOL_TYPE.FUNCTION,
        type: CHAT_GPT_TOOL_TYPE,
    })
    type!: CHAT_GPT_TOOL_TYPE.FUNCTION;

    @Prop({
        required: true,
    })
    function!: ChatGPTFunctionDescriber;
}

export class ChatGPTToolReference_Function extends AutoCastable {
    @Prop({
        required: true,
        default: CHAT_GPT_TOOL_TYPE.FUNCTION,
        type: CHAT_GPT_TOOL_TYPE,
    })
    type!: CHAT_GPT_TOOL_TYPE.FUNCTION;

    @Prop({
        required: true,
        type: Pick(ChatGPTFunctionDescriber, 'name'),
    })
    function!: Pick<ChatGPTFunctionDescriber, 'name'>;
}

export class ChatGPTModelOptions extends AutoCastable {
    static windowSize = 4096;

    @Prop({
        default: 'gpt-3.5-turbo',
    })
    model!: string;

    @Prop({
        required: true,
        desc: 'The messages to generate chat completions for, in the [chat format](/docs/guides/chat/introduction).',
        arrayOf: ChatGPTMessage,
        validateCollection(this: typeof ChatGPTModelOptions, messages: ChatGPTMessage[]) {
            const totalTokens = _.sum(messages.map((m) => countGPTToken(m.content, 'gpt-3.5-turbo')));
            if (totalTokens > this.windowSize) {
                throw new Error(`The total number of tokens in the messages (${totalTokens}) exceeds the maximum window size of ${this.windowSize}`);
            }
            return true;
        },
    })
    messages!: ChatGPTMessage[];

    @Prop({
        desc: 'The maximum number of [tokens](/tokenizer) to generate in the completion.  The token count of your prompt plus `max_tokens` cannot exceed the model\'s context length. Most models have a context length of 2048 tokens (except for the newest models, which support 4096).',
        validate(this: typeof ChatGPTModelOptions, val: number) {
            return val >= 1 && val <= this.windowSize;
        },
    })
    max_tokens?: number;

    @Prop({
        desc: 'What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.  We generally recommend altering this or `top_p` but not both.',
        validate: (val: number) => val >= 0.0 && val <= 2.0,
    })
    temperature?: number;

    @Prop({
        desc: 'An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.  We generally recommend altering this or `temperature` but not both.',
        validate: (val: number) => val >= 0.0 && val <= 1.0,
    })
    top_p?: number;

    @Prop({
        desc: 'How many chat completion choices to generate for each input message.  **Note:** Because this parameter generates many completions, it can quickly consume your token quota. Use carefully and ensure that you have reasonable settings for `max_tokens` and `stop`.',
        validate: (val: number) => val >= 1 && val <= 64,
    })
    n?: number;

    @Prop({
        desc: 'If set, partial message deltas will be sent, like in ChatGPT. Tokens will be sent as data-only [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format) as they become available, with the stream terminated by a `data: [DONE]` message.'
    })
    stream?: boolean;

    @Prop({
        type: [ArrayOf(String), String],
    })
    stop?: string | string[];

    @Prop({
        desc: 'Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model\'s likelihood to talk about new topics.  [See more information about frequency and presence penalties.](/docs/api-reference/parameter-details)',
        validate: (val: number) => val >= -2.0 && val <= 2.0,
    })
    presence_penalty?: number;

    @Prop({
        desc: 'Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model\'s likelihood to repeat the same line verbatim.  [See more information about frequency and presence penalties.](/docs/api-reference/parameter-details)',
        validate: (val: number) => val >= -2.0 && val <= 2.0,
    })
    frequency_penalty?: number;

    @Prop({
        desc: 'Modify the likelihood of specified tokens appearing in the completion.  Accepts a json object that maps tokens (specified by their token ID in the GPT tokenizer) to an associated bias value from -100 to 100. You can use this [tokenizer tool](/tokenizer?view=bpe) (which works for both GPT-2 and GPT-3) to convert text to token IDs. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.  As an example, you can pass `{\"50256\": -100}` to prevent the <|endoftext|> token from being generated.',
        dictOf: Number,
    })
    logit_bias?: Record<string, number>;

    @Prop({
        desc: 'A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids).',
    })
    user?: string;

    @Prop({
        desc: 'An object specifying the format that the model must output. Used to enable JSON mode.',
    })
    response_format?: ChatGPTResponseFormat;

    @Prop({
        desc: 'This feature is in Beta. If specified, our system will make a best effort to sample deterministically, such that repeated requests with the same seed and parameters should return the same result. Determinism is not guaranteed, and you should refer to the system_fingerprint response parameter to monitor changes in the backend.',
        nullable: true
    })
    seed?: number;

    @Prop({
        desc: 'A list of tools the model may call. Currently, only functions are supported as a tool. Use this to provide a list of functions the model may generate JSON inputs for.',
        arrayOf: [ChatGPTToolDescriber_Function],
    })
    tools?: ChatGPTToolDescriber_Function[];

    @Prop({
        desc: `Controls which (if any) function is called by the model. none means the model will not call a function and instead generates a message. auto means the model can pick between generating a message or calling a function.`,
        type: [ChatGPTToolReference_Function, CHAT_GPT_FUNCTION_CALL_MODE]
    })
    tool_choice?: ChatGPTToolReference_Function | CHAT_GPT_FUNCTION_CALL_MODE;

    @Prop({
        desc: 'A list of functions the model may generate JSON inputs for.',
        arrayOf: ChatGPTFunctionDescriber,
    })
    functions?: ChatGPTFunctionDescriber[];

    @Prop({
        desc: `Controls how the model responds to function calls. "none" means the model does not call a function, and responds to the end-user. "auto" means the model can pick between an end-user or calling a function. Specifying a particular function via {"name":\ "my_function"} forces the model to call that function. "none" is the default when no functions are present. "auto" is the default if functions are present.`,
        type: [Pick(ChatGPTFunctionDescriber, 'name'), CHAT_GPT_FUNCTION_CALL_MODE]
    })
    function_call?: { name: string; } | CHAT_GPT_FUNCTION_CALL_MODE;
}

export class ChatGPT16KModelOptions extends ChatGPTModelOptions {
    static override windowSize = 16384;
    @Prop({
        default: 'gpt-3.5-turbo-16k',
    })
    override model!: string;
}

export class ChatGPTResponseStream extends Transform {

    lastEvent?: ChatCompletionChunk;

    get id() {
        return this.lastEvent?.id;
    }
    get crated() {
        return this.lastEvent ? new Date(this.lastEvent.created * 1000) : undefined;
    }
    get model() {
        return this.lastEvent?.model;
    }
    get systemFingerprint() {
        return this.lastEvent?.system_fingerprint;
    }

    get choice() {
        return this.accumulatedObject?.choices?.find((x) => x.index === this.choiceIndex);
    }

    get role(): string | undefined {
        return this.choice?.delta.role;
    }

    history?: LLMMessage;

    finishReason?: string;

    accumulatedObject: ChatCompletionChunk = {} as any;

    constructor(protected choiceIndex: number = 0) {
        super({
            objectMode: true,
            highWaterMark: 4 * 1024,
        });
    }

    applyDelta(ptr: object = this.accumulatedObject, delta?: any, stack: string[] = []) {
        if (typeof delta !== 'object' || delta === null) {
            return;
        }
        for (const [k, v] of Object.entries(delta)) {
            if (Array.isArray(v)) {
                let cur = Reflect.get(ptr, k);
                if (!Array.isArray(cur)) {
                    cur = [];
                    Reflect.set(ptr, k, cur);
                }
                for (const inner of v) {
                    if (typeof inner.index !== 'number') {
                        continue;
                    }
                    let nextHop = Reflect.get(cur, inner.index);
                    if (!nextHop) {
                        nextHop = {};
                        Reflect.set(cur, inner.index, nextHop);
                    }
                    this.applyDelta(nextHop, inner, [...stack, k, inner.index]);
                }
                continue;
            }
            if (typeof v === 'object' && v !== null) {
                let nextHop = Reflect.get(ptr, k);
                if (!nextHop || typeof nextHop !== 'object') {
                    nextHop = {};
                    Reflect.set(ptr, k, nextHop);
                }
                this.applyDelta(nextHop, v, [...stack, k]);
                continue;
            }
            const curVal = Reflect.get(ptr, k);
            if (curVal && typeof v !== typeof curVal) {
                // Bug in OpenAI API or Azure screwed up the protocol
                continue;
            }

            if (typeof v === 'string' && stack.includes('delta')) {
                Reflect.set(ptr, k, `${curVal || ''}${v}`);

                continue;
            }

            Reflect.set(ptr, k, v);
        }
    }

    override _flush(callback: TransformCallback) {
        const choice = this.choice;
        if (choice?.delta.tool_calls) {
            for (const x of choice?.delta.tool_calls) {
                this.emit('tool', x, x.id);
                if (x.type === 'function') {
                    this.emit('call', x.function, x.id);
                }
            }
            this.emit('tools', choice.delta.tool_calls);

            this.push(LLMFunctionCallRequest.from({
                text: this.accumulatedObject.choices[this.choiceIndex].delta.content || '',
                functionCalls: choice.delta.tool_calls.map((x) => {
                    return {
                        id: x.id,
                        name: x.function!.name,
                        arguments: parseJSON(x.function!.arguments as string)
                    };
                }),
            }));
        }
        this.emit('history', choice?.delta);
        this.history = choice?.delta as any;
        this.emit('final', this.accumulatedObject);

        this.push(null);
        callback(null);
    }

    override _transform(input: { data: ChatCompletionChunk | '[DONE]'; } | null, _encoding: string, callback: TransformCallback) {
        if (input === null) {
            return callback(null);
        }

        const chunk = input.data;

        if (typeof chunk === 'string') {
            // '[DONE]'

            return callback(null);
        }
        if (!chunk) {
            return callback(null);
        }

        this.lastEvent = chunk;
        this.emit('event', chunk);

        const choices = [...(chunk.choices || [])].filter((x) => x.index === this.choiceIndex);

        this.applyDelta(this.accumulatedObject, chunk);
        for (const x of choices) {
            if (x.delta.content) {
                this.emit('text', x.delta.content);
                this.push(x.delta.content);
            }

            if (x.finish_reason) {
                this.finishReason = x.finish_reason;
                this.emit('reason', this.finishReason);
            }
        }

        callback(null);
        return;
    }
}

export interface ChatGPTResponseStream extends Transform {
    on(event: 'event', handler: (event: ChatCompletionChunk) => void): this;
    on(event: 'role', handler: (role: NonNullable<ChatCompletionChunk['choices'][0]['delta']['role']>) => void): this;
    on(event: 'text', handler: (textChunk: string) => void): this;
    on(event: 'call', handler: (functionCall: ChatCompletionMessageToolCall['function'], id?: string) => void): this;
    on(event: 'tools', handler: (toolCalls: ChatCompletionMessageToolCall[]) => void): this;
    on(event: 'tool', handler: (toolCall: ChatCompletionMessageToolCall, id: string) => void): this;
    on(event: 'reason', handler: (reason: string) => void): this;
    on(event: 'history', handler: (history: ChatCompletionChunk['choices'][0]['delta']) => void): this;

    once(event: 'event', handler: (event: ChatCompletionChunk) => void): this;
    once(event: 'role', handler: (role: NonNullable<ChatCompletionChunk['choices'][0]['delta']['role']>) => void): this;
    once(event: 'text', handler: (textChunk: string) => void): this;
    once(event: 'call', handler: (functionCall: ChatCompletionMessageToolCall['function'], id?: string) => void): this;
    once(event: 'tools', handler: (toolCalls: ChatCompletionMessageToolCall[]) => void): this;
    once(event: 'tool', handler: (toolCall: ChatCompletionMessageToolCall, id: string) => void): this;
    once(event: 'reason', handler: (reason: string) => void): this;
    once(event: 'history', handler: (history: ChatCompletionChunk['choices'][0]['delta']) => void): this;

    on(event: 'close', listener: () => void): this;
    on(event: 'data', listener: (chunk: any) => void): this;
    on(event: 'drain', listener: () => void): this;
    on(event: 'end', listener: () => void): this;
    on(event: 'error', listener: (err: Error) => void): this;
    on(event: 'finish', listener: () => void): this;
    on(event: 'pause', listener: () => void): this;
    on(event: 'pipe', listener: (src: Readable) => void): this;
    on(event: 'readable', listener: () => void): this;
    on(event: 'resume', listener: () => void): this;
    on(event: 'unpipe', listener: (src: Readable) => void): this;
    on(event: string | symbol, listener: (...args: any[]) => void): this;
    once(event: 'close', listener: () => void): this;
    once(event: 'data', listener: (chunk: any) => void): this;
    once(event: 'drain', listener: () => void): this;
    once(event: 'end', listener: () => void): this;
    once(event: 'error', listener: (err: Error) => void): this;
    once(event: 'finish', listener: () => void): this;
    once(event: 'pause', listener: () => void): this;
    once(event: 'pipe', listener: (src: Readable) => void): this;
    once(event: 'readable', listener: () => void): this;
    once(event: 'resume', listener: () => void): this;
    once(event: 'unpipe', listener: (src: Readable) => void): this;
    once(event: string | symbol, listener: (...args: any[]) => void): this;
}

@injectable()
export class ChatGPT0613 extends AbstractLLM<ChatGPTModelOptions> {
    static override description = 'OpenAI GPT-3.5 (ChatGPT) Model';
    static override aliases = [
        'gpt-3.5-turbo-0613', 'chatgpt-0613', 'gpt3.5-0613', 'gpt35-0613'
    ];
    static override streamingSupported = true;
    static override chatOptimized = true;
    static override systemSupported = true;
    static override modelOptionsType = ChatGPTModelOptions;
    static override windowSize = ChatGPTModelOptions.windowSize;
    static modelName = 'gpt-3.5-turbo-0613';
    static override nSupported = true;
    static override functionCalling = 'native';
    static visionEnabled: boolean = false;

    override clients: Array<OpenAIHTTP> = [];

    logger = this.globalLogger.child({ service: this.constructor.name });

    constructor(
        protected envConfig: EnvConfig,
        protected globalLogger: GlobalLogger,
        protected tempFileManager: TempFileManager,
        protected threadLocal: AsyncLocalContext,
    ) {
        super(...arguments);
    }

    override async init() {
        await this.dependencyReady();
        this.clients = [
            new OpenAIHTTP(this.envConfig.OPENAI_API_KEY),
        ].filter((x) => x?.supportedChatCompletionModels.includes((this.constructor as typeof ChatGPT0613).modelName));
        this.emit('ready');
    }

    override async getFunctionCallMessage(thing: unknown) {
        if (thing instanceof LLMFunctionCallRequest) {
            return {
                role: 'assistant',
                content: `${thing.text || ''}`,
                tool_calls: thing.functionCalls.map((x) => ({
                    id: x.id,
                    type: 'function',
                    function: {
                        name: x.name,
                        arguments: x.arguments,
                    }
                }))
            } as LLMMessage;
        }

        if (thing instanceof LLMFunctionCallResponse) {
            return {
                role: 'tool',
                content: `${typeof thing.content === 'string' ? thing.content : JSON.stringify(thing.content)}`,
                name: thing.name,
                tool_call_id: thing.functionCallId
            } as LLMMessage;
        }

        return super.getFunctionCallMessage(thing);
    }

    override async _run<U extends LLMModelOptions<ChatGPTModelOptions>>(
        client: this['clients'][number],
        prompt: string | PromptChunk[],
        modelOpts?: U,
        requestOptions?: HTTPServiceRequestOptions
    ): Promise<DependsOnOptions<U>> {
        const modelName = (this.constructor as typeof ChatGPT0613).modelName;
        const draftOptions: Partial<ChatGPTModelOptions> = {
            top_p: modelOpts?.top_p,
            max_tokens: modelOpts?.max_tokens,
            temperature: modelOpts?.temperature,
            seed: modelOpts?.seed,
            ...modelOpts?.modelSpecific,
            n: modelOpts?.n || 1,
            stream: modelOpts?.stream,
            model: modelName,
        };
        if (modelOpts?.functions) {
            draftOptions.tools = modelOpts.functions.map((x) => ({
                type: CHAT_GPT_TOOL_TYPE.FUNCTION,
                function: x
            }));
        }
        if (modelOpts?.function_call) {
            draftOptions.tool_choice = typeof modelOpts.function_call === 'string' ?
                modelOpts.function_call as CHAT_GPT_FUNCTION_CALL_MODE : {
                    type: CHAT_GPT_TOOL_TYPE.FUNCTION,
                    function: modelOpts.function_call
                };
        }

        draftOptions.messages ??= [];

        if (modelOpts?.system) {
            draftOptions.messages!.unshift({ role: CHAT_GPT_ROLE.SYSTEM, content: modelOpts.system });
        }

        if (modelOpts?.messages) {
            const ps = modelOpts.messages.map(async (x) => {

                const mixin = {
                    content: await this.encodePromptChunks(x.content),
                    role: x.role,
                    name: x.name,
                };

                if (Array.isArray(mixin.content) && mixin.content?.find((x) => x.type !== 'text')) {
                    if (mixin.role === 'assistant') {

                        mixin.role = 'user';
                        mixin.name ??= 'special-assistant';
                    }
                }

                if (mixin.role !== 'user' && Array.isArray(mixin.content)) {
                    mixin.content = mixin.content.map((x) => x.text).join('\n');
                }

                return {
                    ...x,
                    ...mixin,
                };
            });

            const rs = await Promise.all(ps);

            draftOptions.messages?.push(...rs);
        }

        if (prompt) {
            draftOptions.messages!.push({ role: CHAT_GPT_ROLE.USER, content: await this.encodePromptChunks(prompt) });
        }

        const opts = (this.constructor as typeof ChatGPT0613).modelOptionsType.from(draftOptions);
        const numTokens = countGPTToken(chatMLEncode(stringPromptChunks(prompt), modelOpts));
        this.logger.debug(`Calling ${modelName} by ${client.name}(${client.baseURL}) approx ${numTokens} tokens`);

        if ((numTokens + (opts.max_tokens || 0)) >= this.windowSize) {
            const newMaxTokens = Math.floor(this.windowSize - numTokens - 2);
            if (newMaxTokens < 0) {
                throw new ParamValidationError(`Prompt too long for ${modelName} ${numTokens}/${this.windowSize}`);
            }
            this.logger.warn(`Prompt has ${numTokens} tokens, max_tokens is ${opts.max_tokens}, which is greater than the window size of ${this.windowSize}. Shrinking max_tokens to ${newMaxTokens}.`);
            opts.max_tokens = newMaxTokens;
        }

        const r = await client.chatCompletions(opts as any, requestOptions);

        if (this.threadLocal.ctx?.tokenUsage === undefined) {
            this.threadLocal.ctx.tokenUsage = {};
        }
        if (this.threadLocal.ctx?.tokenUsage[modelName] === undefined) {
            this.threadLocal.ctx.tokenUsage[modelName] = {};
        }

        const usageTrack = this.threadLocal.ctx.tokenUsage[modelName];

        if (opts.stream) {
            this.logger.debug(`Streaming response from ${modelName} by ${client.name}`);
            (r.data as Readable).once('end', () => {
                this.logger.debug(`Streaming completed from ${modelName} by ${client.name}`);
            });

            const streams = _.range(0, opts.n || 1).map(
                (i) =>
                    (r.data as any as Readable).pipe(
                        new ChatGPTResponseStream(i)
                    )
            );

            if (opts.n && opts.n > 1) {

                streams[0].once('end', () => {
                    if (!(r.data as Readable)?.readableEnded) {
                        (r.data as Readable).destroy();
                    }

                    usageTrack.inputTokens ??= 0;
                    usageTrack.outputTokens ??= 0;

                    usageTrack.inputTokens += _.get(streams[0], 'accumulatedObject.usage.prompt_tokens', 0);
                    usageTrack.outputTokens += _.get(streams[0], 'accumulatedObject.usage.completion_tokens', 0);
                });

                return streams as any;
            }

            const onlyStream: ChatGPTResponseStream = streams[0];
            onlyStream.once('end', () => {
                if (!(r.data as Readable)?.readableEnded) {
                    (r.data as Readable).destroy();
                }

                usageTrack.inputTokens ??= 0;
                usageTrack.outputTokens ??= 0;

                usageTrack.inputTokens += _.get(onlyStream.accumulatedObject, 'usage.prompt_tokens', 0);
                usageTrack.outputTokens += _.get(onlyStream.accumulatedObject, 'usage.completion_tokens', 0);
            });

            return onlyStream as any;
        }

        const rData = r.data as any as ChatCompletion;

        usageTrack.inputTokens ??= 0;
        usageTrack.outputTokens ??= 0;

        usageTrack.inputTokens += _.get(rData, 'usage.prompt_tokens', 0);
        usageTrack.outputTokens += _.get(rData, 'usage.completion_tokens', 0);

        this.logger.debug(`Received response from ${modelName} by ${client.name}, ${rData.usage?.completion_tokens} tokens.`);

        const texts = _(rData).get('choices', []).map((x) => {
            if (x.finish_reason === 'content_filter') {
                const filterDetails = (x as any).content_filter_result;
                if (filterDetails) {
                    for (const [k, v] of Object.entries<any>(filterDetails)) {
                        if (v?.filtered) {
                            throw new HarmfulContentError(`Your input is filtered because it provokes ${k}. Please change your input and try again.`);
                        }
                    }
                }
                this.logger.warn(`Received content triggers 'content_filter' restriction`);
                throw new HarmfulContentError('Output possibly includes harmful contents, please check your input.');
            }

            const tool_calls = _.get(x, 'message.tool_calls');
            if (tool_calls && !_.isEmpty(tool_calls)) {
                return LLMFunctionCallRequest.from({
                    functionCalls: tool_calls.map((x) => ({
                        id: x.id,
                        name: x.function.name,
                        arguments: parseJSON(x.function!.arguments as string)
                    })),
                    text: _.get(x, 'message.content') || ''
                });
            }

            return _.get(x, 'message.content') || '';
        });

        if (opts.n && opts.n > 1) {
            return texts as any;
        }

        return texts[0] || '' as any;
    }

    override async encodePromptChunks(promptChunks: string | PromptChunk[] | null): Promise<any> {
        if (!this.interleavedPromptSupported) {
            return super.encodePromptChunks(promptChunks);
        }

        if (typeof promptChunks === 'string') {
            return promptChunks;
        }

        if (!promptChunks) {
            return '';
        }

        const ps = promptChunks.map(async (x) => {
            if (typeof x === 'string') {
                return { type: 'text', text: x };
            }
            if (x instanceof URL) {
                if (x.hostname === 'localhost' || x.hostname.startsWith('127.')) {
                    const tmpPath = this.tempFileManager.alloc();
                    await downloadFile(x.toString(), tmpPath);
                    const buff = await readFile(tmpPath);
                    const mimeVec = await mimeOf(buff);
                    const r = {
                        type: 'image_url',
                        image_url: {
                            url: `data:${mimeVec.mediaType}/${mimeVec.subType};base64,${buff.toString('base64')}`,
                            detail: 'auto',
                        }
                    };
                    this.tempFileManager.bindPathTo(r, tmpPath);

                    return r;
                }

                return {
                    type: 'image_url', image_url: {
                        url: `${x}`,
                        detail: 'auto',
                    }
                };
            }
            if (Buffer.isBuffer(x)) {
                const mimeInfo = await mimeOf(x);
                return {
                    type: 'image_url',
                    image_url: {
                        url: `data:${mimeInfo.mediaType}/${mimeInfo.subType};base64,${x.toString('base64')}`,
                        detail: 'auto',
                    }
                };
            }
            if (x instanceof Blob) {
                return {
                    type: 'image_url',
                    image_url: {
                        url: `data:${x.type};base64,${Buffer.from(await x.arrayBuffer()).toString('base64')}`,
                        detail: 'auto',
                    }
                };
            }

            return { type: 'text', text: JSON.stringify(x) };
        });

        return await Promise.all(ps);
    }

}

@injectable()
export class ChatGPT16K0613 extends ChatGPT0613 implements AbstractLLM<ChatGPT16KModelOptions> {
    static override description = 'OpenAI GPT-3.5 (ChatGPT) Model With 16k Window';
    static override aliases = [
        'gpt3.5-16k-0613', 'chatgpt-16k-0613', 'gpt35-16k-0613', 'gpt-3.5-turbo-16k-0613'
    ];
    static override streamingSupported = true;
    static override chatOptimized = true;
    static override modelOptionsType = ChatGPT16KModelOptions;
    static override windowSize = ChatGPT16KModelOptions.windowSize;
    static override modelName = 'gpt-3.5-turbo-16k';
    static override nSupported = true;

    override clients: Array<OpenAIHTTP> = [];

    override async init() {
        await this.dependencyReady();
        this.clients = [
            new OpenAIHTTP(this.envConfig.OPENAI_API_KEY),
        ].filter((x) => x.supportedChatCompletionModels.includes((this.constructor as typeof ChatGPT16K0613).modelName));

        this.emit('ready');
    }
}

@injectable()
export class ChatGPT0301 extends ChatGPT0613 {
    static override description = 'OpenAI GPT-3.5 (ChatGPT) Model With function call feature';
    static override aliases = ['gpt-3.5-turbo-0301', 'chatgpt-0301', 'gpt3.5-0301'];
    static override streamingSupported = true;
    static override chatOptimized = true;
    static override windowSize = 4096;
    static override modelOptionsType = ChatGPTModelOptions;
    static override modelName = 'gpt-3.5-turbo-0301';
    static override nSupported = true;
    static override functionCalling = 'none';

    override clients: Array<OpenAIHTTP> = [];

    override async init() {
        await this.dependencyReady();
        this.clients = [
            new OpenAIHTTP(this.envConfig.OPENAI_API_KEY),
        ].filter((x) => x.supportedChatCompletionModels.includes((this.constructor as typeof ChatGPT0301).modelName));

        this.emit('ready');
    }
}
