import { ArrayOf, AutoCastable, DownstreamServiceFailureError, isAutoCastableClass, ParamValidationError, Pick, Prop } from 'civkit/civ-rpc';
import { injectable } from 'tsyringe';
import { isReadable, once, Readable } from 'stream';
import { chatMLEncode, FunctionCallingAwareLLMMessage, FunctionCallingAwareLLMModelOptions, LLMFunctionCallRequest, LLMFunctionCallResponse, LLMMessage, LLMModelOptions, LLMPeakStream, parseJSON, PromptChunk, stringPromptChunks } from './misc';
import { AbstractLLM, DependsOnOptions, DetectFunctions, LLMDto } from './base';
import { OpenRouterHTTP } from '../../3rd-party/open-router';
import { EnvConfig } from '../envconfig';
import { GlobalLogger } from '../logger';
import { TempFileManager } from '../temp-file';
import { AsyncLocalContext } from '../async-context';
import { HTTPServiceRequestOptions, downloadFile, isPrimitiveType, mimeOf } from 'civkit';
import { readFile } from 'fs/promises';
import _ from 'lodash';
import { ChatCompletion } from 'openai/resources/index.mjs';
import { countGPTToken } from '../../utils/openai';
import { HarmfulContentError } from '../errors';
import { ChatGPTResponseStream } from './gpt-35';

export enum CHAT_GPT_IMAGE_DETAIL {
    AUTO = 'auto',
    LOW = 'low',
    HIGH = 'high',
}
export class ChatGPTMessageImageUrl extends AutoCastable {
    @Prop({
        desc: 'Either a URL of the image or the base64 encoded image data.',
    })
    url?: string;

    @Prop({
        desc: 'Either a URL of the image or the base64 encoded image data.',
        type: CHAT_GPT_IMAGE_DETAIL,
        default: CHAT_GPT_IMAGE_DETAIL.AUTO,
    })
    detail?: CHAT_GPT_IMAGE_DETAIL | 'string';
}
export class ChatGPTMessageImageUrlChunk extends AutoCastable {
    @Prop({
        desc: 'Type of the message chunk',
        default: 'image_url',
        required: true,
        validate: (x) => x === 'image_url'
    })
    type!: 'image_url';

    @Prop({
        desc: 'The content of the image url chunk',
        required: true,
    })
    image_url!: ChatGPTMessageImageUrl;
}

export enum CHAT_GPT_ROLE {
    USER = 'user',
    SYSTEM = 'system',
    ASSISTANT = 'assistant',
    FUNCTION = 'function',
    TOOL = 'tool',
}
export class ChatGPTMessageTextChunk extends AutoCastable {
    @Prop({
        desc: 'Type of the message chunk',
        default: 'text',
        required: true,
        validate: (x) => x === 'text'
    })
    type!: 'text';

    @Prop({
        desc: 'The content of the message chunk',
        required: true,
    })
    text!: string;
}

export interface ChatGPTFunctionCall {
    name: string;
    // The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
    arguments: string;
}
export class ChatGPTToolCall_Function extends AutoCastable {
    @Prop({
        desc: 'The ID of the tool call',
        required: true,
    })
    id!: string;

    @Prop({
        desc: 'The type of the tool. Currently, only function is supported.',
        required: true,
        default: 'function',
    })
    type!: string;

    @Prop({
        desc: `The function that the model called.`,
        required: true,
    })
    function!: ChatGPTFunctionCall;

    @Prop()
    index?: number;
}
export class ChatGPTMessage extends AutoCastable {
    @Prop({
        desc: 'The role of the author of this message.',
        required: true,
        default: 'user',
        type: CHAT_GPT_ROLE,
    })
    role!: CHAT_GPT_ROLE | string;

    @Prop({
        desc: 'The contents of the message',
        default: '',
        nullable: true,
        type: [ArrayOf(ChatGPTMessageTextChunk, ChatGPTMessageImageUrlChunk), String],
    })
    content!: string | (ChatGPTMessageTextChunk | ChatGPTMessageImageUrlChunk)[];

    @Prop({
        desc: 'The name of the user in a multi-user chat'
    })
    name?: string;

    @Prop({
        desc: 'The tool calls generated by the model, such as function calls.',
        arrayOf: [ChatGPTToolCall_Function],
    })
    tool_calls?: (ChatGPTToolCall_Function)[];

    @Prop({
        desc: 'The name and arguments of a function that should be called, as generated by the model.',
    })
    function_call?: ChatGPTFunctionCall;

    @Prop({
        desc: 'Tool call that this message is responding to.',
    })
    tool_call_id?: string;
}
export enum CHAT_GPT_TOOL_TYPE {
    FUNCTION = 'function',
}
export class ChatGPTFunctionDescriber extends AutoCastable {
    @Prop({
        desc: 'The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.',
        validate: (x: string) => /[a-zA-Z0-9_]{1,64}/.test(x),
        required: true
    })
    name!: string;

    @Prop({
        desc: 'The description of what the function does.',
        default: ''
    })
    description!: string;

    @Prop({
        desc: 'The parameters the functions accepts, described as a JSON Schema object. See the guide for examples, and the JSON Schema reference for documentation about the format.',
        required: true,
    })
    parameters!: object;
}
export class ChatGPTToolDescriber_Function extends AutoCastable {
    @Prop({
        required: true,
        default: CHAT_GPT_TOOL_TYPE.FUNCTION,
        type: CHAT_GPT_TOOL_TYPE,
    })
    type!: CHAT_GPT_TOOL_TYPE.FUNCTION;

    @Prop({
        required: true,
    })
    function!: ChatGPTFunctionDescriber;
}
export class ChatGPTToolReference_Function extends AutoCastable {
    @Prop({
        required: true,
        default: CHAT_GPT_TOOL_TYPE.FUNCTION,
        type: CHAT_GPT_TOOL_TYPE,
    })
    type!: CHAT_GPT_TOOL_TYPE.FUNCTION;

    @Prop({
        required: true,
        type: Pick(ChatGPTFunctionDescriber, 'name'),
    })
    function!: Pick<ChatGPTFunctionDescriber, 'name'>;
}
export enum CHAT_GPT_FUNCTION_CALL_MODE {
    NONE = 'none',
    AUTO = 'auto',
}

export enum OPENROUTER_REASONING_EFFORT {
    HIGH = 'high',
    MEDIUM = 'medium',
    LOW = 'low',
}
export class OpenRouterReasoningOptions extends AutoCastable {
    @Prop({
        type: OPENROUTER_REASONING_EFFORT,
    })
    effort?: OPENROUTER_REASONING_EFFORT;
    @Prop()
    max_tokens?: number;
    @Prop()
    exclude?: boolean;
    @Prop()
    enabled?: boolean;
}

// Definitions of subtypes are below
export class OpenRouterRequestOptions extends AutoCastable {
    static contextLength = 8192;

    // Either "messages" or "prompt" is required
    @Prop({
        arrayOf: ChatGPTMessage
    })
    messages?: ChatGPTMessage[];
    @Prop()
    prompt?: string;
    @Prop()
    reasoning?: OpenRouterReasoningOptions;

    // If "model" is unspecified, uses the user's default
    @Prop()
    model?: string; // See "Supported Models" section

    // Allows to force the model to produce specific output format.
    // See models page and note on this docs page for which models support it.
    @Prop()
    response_format?: { type: 'json_object' | string; };

    @Prop({
        type: [ArrayOf(String), String],
    })
    stop?: string | string[];
    @Prop()
    stream?: boolean; // Enable streaming

    // See LLM Parameters (openrouter.ai/docs/api-reference/parameters)
    @Prop({
        validate(this: typeof OpenRouterRequestOptions, v: number) { return v >= 1 && v <= this.contextLength; }
    })
    max_tokens?: number; // Range: [1, context_length)
    @Prop({
        validate: (v: number) => v >= 0 && v <= 2,
    })
    temperature?: number; // Range: [0, 2]

    // Tool calling
    // Will be passed down as-is for providers implementing OpenAI's interface.
    // For providers with custom interfaces, we transform and map the properties.
    // Otherwise, we transform the tools into a YAML template. The model responds with an assistant message.
    // See models supporting tool calling: openrouter.ai/models?supported_parameters=tools
    @Prop({
        arrayOf: ChatGPTToolDescriber_Function,
    })
    tools?: ChatGPTToolDescriber_Function[];
    @Prop({
        type: [ChatGPTToolReference_Function, CHAT_GPT_FUNCTION_CALL_MODE]
    })
    tool_choice?: ChatGPTToolReference_Function | CHAT_GPT_FUNCTION_CALL_MODE;

    // Advanced optional parameters
    @Prop({
        validate: (v: number) => Number.isInteger(v)
    })
    seed?: number; // Integer only
    @Prop({
        validate: (v: number) => v > 0 && v < 1
    })
    top_p?: number; // Range: (0, 1]
    @Prop({
        validate: (v: number) => v >= 1
    })
    top_k?: number; // Range: [1, Infinity) Not available for OpenAI models
    @Prop({
        validate: (v: number) => v >= -2 && v <= 2
    })
    frequency_penalty?: number; // Range: [-2, 2]
    @Prop({
        validate: (v: number) => v >= -2 && v <= 2
    })
    presence_penalty?: number; // Range: [-2, 2]
    @Prop({
        validate: (v: number) => v > 0 && v < 2
    })
    repetition_penalty?: number; // Range: (0, 2]
    @Prop({
        dictOf: Number
    })
    logit_bias?: { [key: string]: number; };
    @Prop({
        validate: (v: number) => Number.isInteger(v) && v > 0 && v < 20
    })
    top_logprobs?: number; // Integer only
    @Prop({
        validate: (v: number) => v >= 0 && v <= 1
    })
    min_p?: number; // Range: [0, 1]
    @Prop({
        validate: (v: number) => v >= 0 && v <= 1
    })
    top_a?: number; // Range: [0, 1]

    // Reduce latency by providing the model with a predicted output
    // https://platform.openai.com/docs/guides/latency-optimization#use-predicted-outputs
    @Prop()
    prediction?: { type: 'content'; content: string; };

    // OpenRouter-only parameters
    // See "Prompt Transforms" section: openrouter.ai/docs/transforms
    @Prop({ arrayOf: String })
    transforms?: string[];
    // See "Model Routing" section: openrouter.ai/docs/model-routing
    @Prop({
        arrayOf: String
    })
    models?: string[];
    // See "Provider Routing" section: openrouter.ai/docs/provider-routing
    @Prop()
    provider?: ProviderPreferences;
    @Prop()
    user?: string; // A stable identifier for your end-users. Used to help detect and prevent abuse.
};

type ProviderPreferences = {
    order?: string[];
    allow_fallbacks?: boolean;
    require_parameters?: boolean;
    data_collection?: 'allow' | 'deny';
    only?: string[];
    ignore?: string[];
    quantizations?: string[];
    sort?: string;
    max_price?: {
        prompt?: number;
        completion?: number;
        image?: number;
    };
};


// Definitions of subtypes are below
export type OpenRouterChatCompletionResponse = {
    id: string;
    // Depending on whether you set "stream" to "true" and
    // whether you passed in "messages" or a "prompt", you
    // will get a different output shape
    choices: (NonStreamingChoice | StreamingChoice | NonChatChoice)[];
    created: number; // Unix timestamp
    model: string;
    object: 'chat.completion' | 'chat.completion.chunk';

    system_fingerprint?: string; // Only present if the provider supports it

    // Usage data is always returned for non-streaming.
    // When streaming, you will get one usage object at
    // the end accompanied by an empty choices array.
    usage?: ResponseUsage;
};

// If the provider returns usage, we pass it down
// as-is. Otherwise, we count using the GPT-4 tokenizer.

type ResponseUsage = {
    /** Including images and tools if any */
    prompt_tokens: number;
    /** The tokens generated */
    completion_tokens: number;
    /** Sum of the above two fields */
    total_tokens: number;
};

// Subtypes:
type NonChatChoice = {
    index: number;
    finish_reason: string | null;
    text: string;
    error?: ErrorResponse;
};

type NonStreamingChoice = {
    index: number;
    finish_reason: string | null;
    native_finish_reason: string | null;
    message: {
        content: string | null;
        role: string;
        tool_calls?: ToolCall[];
    };
    error?: ErrorResponse;
};

type StreamingChoice = {
    index: number;
    finish_reason: string | null;
    native_finish_reason: string | null;
    delta: {
        content: string | null;
        role?: string;
        tool_calls?: ToolCall[];
    };
    error?: ErrorResponse;
};

type ErrorResponse = {
    code: number; // See "Error Handling" section
    message: string;
    metadata?: Record<string, unknown>; // Contains additional error information such as provider details, the raw error message, etc.
};

type ToolCall = {
    id: string;
    type: 'function';
    function: FunctionCall;
};

type FunctionCall = {
    name: string;
    // The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
    arguments: string;
};



@injectable()
export class OpenRouterLLM extends AbstractLLM<OpenRouterRequestOptions> {
    static override description = 'OpenRouter LLM';
    static override aliases = [
        'open-router'
    ];
    static override streamingSupported = true;
    static override chatOptimized = true;
    static override systemSupported = true;
    static override modelOptionsType = OpenRouterRequestOptions;
    static override windowSize = OpenRouterRequestOptions.contextLength;
    static modelName = 'open-router';
    static override functionCalling = 'native';

    override clients: Array<OpenRouterHTTP> = [];

    logger = this.globalLogger.child({ service: this.constructor.name });

    constructor(
        protected envConfig: EnvConfig,
        protected globalLogger: GlobalLogger,
        protected tempFileManager: TempFileManager,
        protected threadLocal: AsyncLocalContext,
    ) {
        super(...arguments);
    }

    override async init() {
        await this.dependencyReady();
        this.clients = [
            new OpenRouterHTTP(this.envConfig.OPENROUTER_API_KEY),
        ];
        this.emit('ready');
    }

    override async getFunctionCallMessage(thing: unknown) {
        if (thing instanceof LLMFunctionCallRequest) {
            return {
                role: 'assistant',
                content: `${thing.text || ''}`,
                tool_calls: thing.functionCalls.map((x) => ({
                    id: x.id,
                    type: 'function',
                    function: {
                        name: x.name,
                        arguments: x.arguments,
                    }
                }))
            } as LLMMessage;
        }

        if (thing instanceof LLMFunctionCallResponse) {
            return {
                role: 'tool',
                content: `${typeof thing.content === 'string' ? thing.content : JSON.stringify(thing.content)}`,
                name: thing.name,
                tool_call_id: thing.functionCallId
            } as LLMMessage;
        }

        return super.getFunctionCallMessage(thing);
    }

    override async _run<U extends LLMModelOptions<OpenRouterRequestOptions>>(
        client: this['clients'][number],
        prompt: string | PromptChunk[],
        modelOpts?: U,
        requestOptions?: HTTPServiceRequestOptions
    ): Promise<DependsOnOptions<U>> {
        const modelName = (this.constructor as typeof OpenRouterLLM).modelName;
        const draftOptions: Partial<OpenRouterRequestOptions> = {
            top_p: modelOpts?.top_p,
            max_tokens: modelOpts?.max_tokens,
            temperature: modelOpts?.temperature,
            seed: modelOpts?.seed,
            ...modelOpts?.modelSpecific,
            stream: modelOpts?.stream,
            model: modelName,
        };
        if (modelOpts?.functions) {
            draftOptions.tools = modelOpts.functions.map((x) => ({
                type: CHAT_GPT_TOOL_TYPE.FUNCTION,
                function: x
            }));
        }
        if (modelOpts?.function_call) {
            draftOptions.tool_choice = typeof modelOpts.function_call === 'string' ?
                modelOpts.function_call as CHAT_GPT_FUNCTION_CALL_MODE : {
                    type: CHAT_GPT_TOOL_TYPE.FUNCTION,
                    function: modelOpts.function_call
                };
        }

        draftOptions.messages ??= [];

        if (modelOpts?.system) {
            draftOptions.messages!.unshift({ role: CHAT_GPT_ROLE.SYSTEM, content: modelOpts.system });
        }

        if (modelOpts?.messages) {
            const ps = modelOpts.messages.map(async (x) => {

                const mixin = {
                    content: await this.encodePromptChunks(x.content),
                    role: x.role,
                    name: x.name,
                };

                if (Array.isArray(mixin.content) && mixin.content?.find((x) => x.type !== 'text')) {
                    if (mixin.role === 'assistant') {

                        mixin.role = 'user';
                        mixin.name ??= 'special-assistant';
                    }
                }

                if (mixin.role !== 'user' && Array.isArray(mixin.content)) {
                    mixin.content = mixin.content.map((x) => x.text).join('\n');
                }

                return {
                    ...x,
                    ...mixin,
                };
            });

            const rs = await Promise.all(ps);

            draftOptions.messages?.push(...rs);
        }

        if (prompt) {
            draftOptions.messages!.push({ role: CHAT_GPT_ROLE.USER, content: await this.encodePromptChunks(prompt) });
        }

        const opts = (this.constructor as typeof OpenRouterLLM).modelOptionsType.from(draftOptions);
        const numTokens = countGPTToken(chatMLEncode(stringPromptChunks(prompt), modelOpts));
        this.logger.debug(`Calling ${modelName} by ${client.name}(${client.baseURL}) approx ${numTokens} tokens`);

        if ((numTokens + (opts.max_tokens || 0)) >= this.windowSize) {
            const newMaxTokens = Math.floor(this.windowSize - numTokens - 2);
            if (newMaxTokens < 0) {
                throw new ParamValidationError(`Prompt too long for ${modelName} ${numTokens}/${this.windowSize}`);
            }
            this.logger.warn(`Prompt has ${numTokens} tokens, max_tokens is ${opts.max_tokens}, which is greater than the window size of ${this.windowSize}. Shrinking max_tokens to ${newMaxTokens}.`);
            opts.max_tokens = newMaxTokens;
        }

        const r = await client.chatCompletions(opts as any, requestOptions);

        let usageTrack: Record<string, any> = {};
        if (this.threadLocal.available()) {
            if (this.threadLocal.ctx?.tokenUsage === undefined) {
                this.threadLocal.ctx.tokenUsage = {};
            }
            if (this.threadLocal.ctx?.tokenUsage[modelName] === undefined) {
                this.threadLocal.ctx.tokenUsage[modelName] = {};
            }
            usageTrack = this.threadLocal.ctx.tokenUsage[modelName];
        }

        if (opts.stream) {
            this.logger.debug(`Streaming response from ${modelName} by ${client.name}`);
            (r.data as Readable).once('end', () => {
                this.logger.debug(`Streaming completed from ${modelName} by ${client.name}`);
            });



            const onlyStream: ChatGPTResponseStream = (r.data as any as Readable).pipe(
                new ChatGPTResponseStream(0)
            );
            onlyStream.once('end', () => {
                if (!(r.data as Readable)?.readableEnded) {
                    (r.data as Readable).destroy();
                }

                usageTrack.inputTokens ??= 0;
                usageTrack.outputTokens ??= 0;

                usageTrack.inputTokens += _.get(onlyStream.accumulatedObject, 'usage.prompt_tokens', 0);
                usageTrack.outputTokens += _.get(onlyStream.accumulatedObject, 'usage.completion_tokens', 0);
            });

            return onlyStream as any;
        }

        const rData = r.data as any as ChatCompletion;

        usageTrack.inputTokens ??= 0;
        usageTrack.outputTokens ??= 0;

        usageTrack.inputTokens += _.get(rData, 'usage.prompt_tokens', 0);
        usageTrack.outputTokens += _.get(rData, 'usage.completion_tokens', 0);

        this.logger.debug(`Received response from ${modelName} by ${client.name}, ${rData.usage?.completion_tokens} tokens.`);

        const texts = _(rData).get('choices', []).map((x) => {
            if (x.finish_reason === 'content_filter') {
                const filterDetails = (x as any).content_filter_result;
                if (filterDetails) {
                    for (const [k, v] of Object.entries<any>(filterDetails)) {
                        if (v?.filtered) {
                            throw new HarmfulContentError(`Your input is filtered because it provokes ${k}. Please change your input and try again.`);
                        }
                    }
                }
                this.logger.warn(`Received content triggers 'content_filter' restriction`);
                throw new HarmfulContentError('Output possibly includes harmful contents, please check your input.');
            }

            const tool_calls = _.get(x, 'message.tool_calls');
            if (tool_calls) {
                return LLMFunctionCallRequest.from({
                    functionCalls: tool_calls.map((x) => ({
                        id: x.id,
                        name: x.function.name,
                        arguments: parseJSON(x.function!.arguments as string)
                    })),
                    text: _.get(x, 'message.content') || ''
                });
            }

            return _.get(x, 'message.content') || '';
        });

        return texts[0] || '' as any;
    }

    override async encodePromptChunks(promptChunks: string | PromptChunk[] | null): Promise<any> {
        if (!this.interleavedPromptSupported) {
            return super.encodePromptChunks(promptChunks);
        }

        if (typeof promptChunks === 'string') {
            return promptChunks;
        }

        if (!promptChunks) {
            return '';
        }

        const ps = promptChunks.map(async (x) => {
            if (typeof x === 'string') {
                return { type: 'text', text: x };
            }
            if (x instanceof URL) {
                if (x.hostname === 'localhost' || x.hostname.startsWith('127.')) {
                    const tmpPath = this.tempFileManager.alloc();
                    await downloadFile(x.toString(), tmpPath);
                    const buff = await readFile(tmpPath);
                    const mimeVec = await mimeOf(buff);
                    const r = {
                        type: 'image_url',
                        image_url: {
                            url: `data:${mimeVec.mediaType}/${mimeVec.subType};base64,${buff.toString('base64')}`,
                            detail: 'auto',
                        }
                    };
                    this.tempFileManager.bindPathTo(r, tmpPath);

                    return r;
                }

                return {
                    type: 'image_url', image_url: {
                        url: `${x}`,
                        detail: 'auto',
                    }
                };
            }
            if (Buffer.isBuffer(x)) {
                const mimeInfo = await mimeOf(x);
                return {
                    type: 'image_url',
                    image_url: {
                        url: `data:${mimeInfo.mediaType}/${mimeInfo.subType};base64,${x.toString('base64')}`,
                        detail: 'auto',
                    }
                };
            }
            if (x instanceof Blob) {
                return {
                    type: 'image_url',
                    image_url: {
                        url: `data:${x.type};base64,${Buffer.from(await x.arrayBuffer()).toString('base64')}`,
                        detail: 'auto',
                    }
                };
            }

            return { type: 'text', text: JSON.stringify(x) };
        });

        return await Promise.all(ps);
    }

    override async structured<U extends (typeof LLMDto), MO extends FunctionCallingAwareLLMModelOptions<OpenRouterRequestOptions>>(
        expectOutputClass: U,
        input: string | FunctionCallingAwareLLMMessage[],
        modelOpts?: MO,
        execOpts?: {
            maxTry?: number;
            requestOptions?: HTTPServiceRequestOptions,
            delayFactor?: number;
            reverseProviderPreference?: boolean;
            filterClients?: (client: OpenRouterHTTP) => boolean;
            asyncValidate?: (parsed: InstanceType<U>, raw: string) => Promise<boolean>;
            peekStream?: LLMPeakStream;
            peekChannel?: string;
            collectRawOutput?: (rawOutput: any) => void;
            collectRawInput?: (
                options: FunctionCallingAwareLLMModelOptions<unknown>,
                prompt?: string | PromptChunk[],
            ) => void;
        }
    ): Promise<DetectFunctions<MO, InstanceType<U>>> {
        const messages: LLMModelOptions<OpenRouterRequestOptions>['messages'] = [
            ...(
                typeof input === 'string' ?
                    [{ role: 'user', content: input }] :
                    await Promise.all(
                        input.map(
                            (x) => {
                                if ((x as LLMMessage).role) {
                                    return x as LLMMessage;
                                }
                                return this.getFunctionCallMessage(x);
                            }
                        )
                    )
            )
        ];
        if (modelOpts?.messages?.length) {
            messages.push(...await Promise.all(
                modelOpts.messages.map(
                    (x) => {
                        if ((x as LLMMessage).role) {
                            return x as LLMMessage;
                        }
                        return this.getFunctionCallMessage(x);
                    }
                )
            ));
        }
        const expectedObjectLike = isAutoCastableClass(expectOutputClass);
        let lastError = '';
        let triesLeft = execOpts?.maxTry || 3;
        let trick: undefined | 'jsonMode' = expectedObjectLike ? 'jsonMode' : undefined;

        while (triesLeft > 0) {
            triesLeft -= 1;
            if (lastError) {
                execOpts?.peekStream?.write({
                    event: 'retry',
                    id: execOpts.peekChannel ? `${execOpts.peekChannel}-${Reflect.get(execOpts.peekStream, 'n') || 0 + 1}` : undefined
                });
            }

            let ret: any;
            if (trick === undefined) {
                const opts = {
                    ...modelOpts,
                    messages,
                    n: 1
                };
                ret = await this.exec('', opts, execOpts as any);
                execOpts?.collectRawInput?.(opts, '');
            } else if (trick === 'jsonMode') {
                let system = modelOpts?.system || '';
                if (
                    !system.includes('JSON') &&
                    !((modelOpts?.messages?.find((x) => (x as LLMMessage).role === 'system') as LLMMessage)?.content?.includes('JSON'))
                ) {
                    system = `${system ? `${system}\n` : ''}${expectedObjectLike ? expectOutputClass?.toJSONModeSystemPromptFragment() : `Provide your response in the following JSON Schema: ${JSON.stringify({
                        type: 'object',
                        properties: {
                            data: {
                                type: expectOutputClass.name.toLowerCase(),
                                description: `The expected output`
                            }
                        }
                    })}`}`;
                }
                const opts = {
                    ...modelOpts,
                    modelSpecific: {
                        response_format: { type: 'json_object' }
                    },
                    messages,
                    n: 1,
                    system,
                };
                ret = await this.exec('', opts, execOpts as any) as string;
                execOpts?.collectRawInput?.(opts, '');
            }
            execOpts?.collectRawOutput?.(ret);

            const textChunks: string[] = [];
            if (isReadable(ret as Readable)) {
                let lastNonTextChunk;
                (ret as Readable).on('data', (c: any) => {
                    if (typeof c === 'string') {
                        textChunks.push(c);
                        execOpts?.peekStream?.write({
                            event: 'chunk',
                            data: c,
                            id: execOpts.peekChannel ? `${execOpts.peekChannel}-${Reflect.get(execOpts.peekStream, 'n') || 0 + 1}` : undefined
                        });
                    } else {
                        lastNonTextChunk = c;
                    }
                });
                await once(ret, 'end');
                ret = lastNonTextChunk || textChunks.join('');
            }
            execOpts?.peekStream?.write({
                event: 'response',
                data: ret,
                id: execOpts.peekChannel ? `${execOpts.peekChannel}-${Reflect.get(execOpts.peekStream, 'n') || 0 + 1}` : undefined
            });

            if (ret instanceof LLMFunctionCallRequest) {
                return ret as any;
            } else if (typeof ret === 'string') {
                messages.push({
                    role: 'assistant',
                    content: ret,
                });
            }

            let structure: InstanceType<U>;
            try {
                structure = expectOutputClass.fromString ? expectOutputClass.fromString(ret as string) as InstanceType<U> :
                    isPrimitiveType(expectOutputClass) ?
                        expectOutputClass.call(undefined, ret) as InstanceType<U> :
                        Reflect.construct(expectOutputClass, [ret]) as InstanceType<U>;
            } catch (err: any) {
                lastError = err?.readableMessage || err?.message || 'Invalid response';
                const errorMsg = `[SYSTEM] Error: ${lastError}\nTry again. Note: this is a system message. DO NOT REPLY.`;
                execOpts?.peekStream?.write({
                    event: 'exception',
                    data: errorMsg,
                    id: execOpts.peekChannel ? `${execOpts.peekChannel}-${Reflect.get(execOpts.peekStream, 'n') || 0 + 1}` : undefined
                });
                messages.push({ role: CHAT_GPT_ROLE.USER, content: errorMsg });

                continue;
            }

            if (execOpts?.asyncValidate) {
                try {
                    execOpts?.peekStream?.write({
                        event: 'check',
                        id: execOpts.peekChannel ? `${execOpts.peekChannel}-${Reflect.get(execOpts.peekStream, 'n') || 0 + 1}` : undefined
                    });
                    const validated = await execOpts.asyncValidate(
                        structure as any,
                        ret || ''
                    );

                    if (!validated) {
                        throw new Error('Invalid response');
                    }
                } catch (err: any) {
                    lastError = err?.readableMessage || err?.message || 'Invalid response';
                    const errorMsg = `[SYSTEM] Error: ${lastError}\nTry again. Note: this is a system message. DO NOT REPLY.`;
                    execOpts?.peekStream?.write({
                        event: 'exception',
                        data: errorMsg,
                        id: execOpts.peekChannel ? `${execOpts.peekChannel}-${Reflect.get(execOpts.peekStream, 'n') || 0 + 1}` : undefined
                    });
                    messages.push({ role: 'user', content: errorMsg });
                    continue;
                }
            }
            execOpts?.peekStream?.write({
                event: 'result',
                data: structure,
                id: execOpts.peekChannel ? `${execOpts.peekChannel}-${Reflect.get(execOpts.peekStream, 'n') || 0 + 1}` : undefined
            });

            return structure as any;
        }

        throw new DownstreamServiceFailureError(`Failed to parse ${expectOutputClass.name} from LLM: ${lastError}`);
    }
}